[package]
name = "jirai"
version = "0.1.0"
edition = "2024"
author = ["Alyx Shang"]
description= "A text-markup language inspired by Jirai Kei."
homepage = "https://github.com/alyxshang/jirai"
repository = "https://github.com/alyxshang/jirai"
readme = "README.markdown"
